#!/bin/bash
 
rm /tmp/screen.png
IMAGE=/tmp/screen.png

BLUR="-blur 2x3" 
PIXEL="-scale 25% -scale 400%" 
GRAY="-colorspace Gray -gamma 0.7"
SEPIA="-sepia-tone 80%"
CHARCOAL="-charcoal 5"
PAINT="-paint 1"
SPREAD="-interpolate nearest -virtual-pixel mirror -spread 250"
VIGNETTE="-background black -vignette 0x5" 

scrot $IMAGE
convert $IMAGE $SPREAD $IMAGE
i3lock -i $IMAGE